version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:4.4.3
    restart: unless-stopped
    volumes:
      - db:/data/db
  app:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017/my_db
      JWT_SECRET: 8hEnPGeoBqGUT6zksxt4G95gW+uMdzwe7EVaRnp0xRI=
      JWT_EXPIRES_IN: 90d
      EMAIL_FROM: ha4900109@gmail.com
      EMAIL_PASSWORD: sfif ixdt kkuf gbhe
      NODE_ENV: production

    depends_on:
      - mongo_db
volumes:
  db:
